### ISSUE TITLE
Enhancement request - Option to turn a string of emojis into a horizontal, single image instead of multiple seperate images

### ISSUE THREAD

**Issue by Iceenice** [EpicGazel/DiscordFreeEmojis#11]
As it says in the title. Instead of typing in multiple emojis and the plugin turning them into separate images, this option would create a single horizontal image with the emojis used -- similar to how messages with only emojis are typically displayed in Discord

**Comment by EpicGazel** [comment]
I consider that outside of the scope of maintaining this project. If someone else wants to tackle it and add a settings toggle, I'd be fine merging it.
