### ISSUE TITLE
Nitro Ads still showing

### ISSUE THREAD

**Issue by Lexiconmancer** [EpicGazel/DiscordFreeEmojis#16]
***In case you don't know where the bug is in the code or what exactly causes it.***

I believe it's not in the code

**Describe the bug**
Nitro ads still show up when hovering emoji menu

**To Reproduce**
Currently not using other plugins. 

Should just need to select the emoji menu in the standard text entry field and then scroll through nitro shareable icons a bit while not having nitro.

**Expected behavior**
According to the custom css included in the useful.css file, ads should not be displayed.

**Screenshots**

https://imgur.com/a/FeXCCi7

**Client:**
 - Win10 Pro
 - Discord Build - Release
 - Plugin Version - uh, current. I don't see version numbers for this.
 - BD Version - current as of 18 Sep 24

**Additional context**

Thanks a lot for maintaining this. Just still seeing some amount of the Nitro ads and would love to have them gone. Thanks again for all your good work!

**Comment by EpicGazel** [comment]
Check the version in Settings (gear icon), BETTERDISCORD, Plugins, DiscordFreeEmojis. It should say v1.8.0.
![Screenshot 2024-09-19 022932-small](https://github.com/user-attachments/assets/b02af956-4569-43cf-9dd4-90e8a7a28192)

**Comment by EpicGazel** [comment]
Stale, assumption is updating fixed the issue.
