### ISSUE TITLE
emojis turn into gifs - is it normal?

### ISSUE THREAD

**Issue by sclmi** [EpicGazel/DiscordFreeEmojis#18]
i installed the plugin properly but once activating it, the emojis i use turn into gifs. i don't know if that's what the plugin is supposed to do, or if i did something wrong in the installation.

**Client:**
 - Windows 11
 - Discord : Latest Version (Release)
 - Plugin : Release Version

**Comment by EpicGazel** [comment]
Static emojis are embedded as images and animated as gifs. This is expected behavior.
