### ISSUE TITLE
Gif emotes not animating anymore

### ISSUE THREAD

**Issue by Xaenchan** [EpicGazel/DiscordFreeEmojis#20]
***In case you don't know where the bug is in the code or what exactly causes it.***

**Describe the bug**
Posting an animated emote only shows the first frame with this plugin, was working some days ago
Guess one of the updates changed something after I restarted discord

if i use 
`[᲼](https://cdn.discordapp.com/emojis/112233445566.gif?&index=0)`
instead of 
`[᲼](https://cdn.discordapp.com/emojis/112233445566.gif?quality=lossless)`

for gif emote

it behaves as previously and animated emote again

Updated better discord and the plugin to the latest version 1.8

**Comment by DanzoGit** [comment]
That's weird. The image animates like this:

`[󠄀](https://cdn.discordapp.com/emojis/1140689203450097705.gif?index=10859&quality=lossless&size=64)`

But it doesn't animate like this:

`[󠄀](https://cdn.discordapp.com/emojis/1140689203450097705.gif?quality=lossless&index=10859&size=64)`

I just swapped the parameters.

**Comment by DanzoGit** [comment]
Sometimes it also helps to change the index to a different number. So far I have removed the index parameter from the code and the animation works fine.

**Comment by EpicGazel** [comment]
Fixed in ea7ac4f5db423b8a8d5859699852b8cc723c88f7.
