### ISSUE TITLE
invisible emotes 

### ISSUE THREAD

**Issue by AliCreature** [EpicGazel/DiscordFreeEmojis#22]
when ever I use an emote it shows as nothing 
![image](https://github.com/user-attachments/assets/2f56c804-89be-4221-9ba1-57fcf8542c17)

- Discord Version Stable 337154 (65fd300) 
- Plugin Version 1.8.0
- Better Discord Version 1.10.2

This issue started happening today

**Comment by DanzoGit** [comment]
Hmm. Images from the domain [cdn.discordapp.com](cdn.discordapp.com) are no longer embedded.

**Comment by EpicGazel** [comment]
Update and tell me if the issue persists.

**Comment by AliCreature** [comment]
can confirm just started working again
