### ISSUE TITLE
idk if this is normal or not but the emojis are big

### ISSUE THREAD

**Issue by superfan6000** [EpicGazel/DiscordFreeEmojis#26]
***In case you don't know where the bug is in the code or what exactly causes it.***

**Describe the bug**

**To Reproduce**
`If you use other plugins, disable all of them to figure out which ones are necessary to reproduce your issue, if any.`

`Make sure you can reproduce this problem yourself with your steps after restarting Discord!`

**Expected behavior**

**Screenshots**
Check Ctrl-Shift-I console for red error logs!

**Client:**
 - Browser [which browser] / Desktop [OS]
 - Discord Build Channel [Release / PTB / Canary]
 - Plugin Version [e.g. 1.2]
 - BD Version (if applicable)

**Additional context**

**Comment by EpicGazel** [comment]
Open the settings and turn off "Use native emoji size".
