### ISSUE TITLE
Automod Blocking Emojis in Discord Server. Looking for solutions. 

### ISSUE THREAD

**Issue by Thebomb32** [EpicGazel/DiscordFreeEmojis#4]
The mods in a discord server that I am active in recently updated their automod to block markdown embeds. 
![image](https://github.com/EpicGazel/DiscordFreeEmojis/assets/152790071/38c725e2-7a1b-45f9-86ab-e60ee8793a93)
![image](https://github.com/EpicGazel/DiscordFreeEmojis/assets/152790071/d2278fb3-3361-43f9-b6c3-8f87bcbda837)

There is the rule they have added.

Wondering if there is any bypass that can be achieved to get around this.

Thanks,

**Comment by Thebomb32** [comment]
Solved.

Changed code to 

function replaceEmoji(parseResult, emoji) {
    const emojiUrl = `https://cdn.discordapp.com/emojis/${emoji.id}.${emoji.animated ? "gif" : "webp"}`;
    parseResult.content = parseResult.content.replace(
        `<${emoji.animated ? "a" : ""}:${emoji.originalName || emoji.name}:${emoji.id}>`,
        `[\\\]](${emojiUrl + '?size=48'})  `
    );
}

**Comment by Thebomb32** [comment]
If for some reason that does not work there is an alternative

function replaceEmoji(parseResult, emoji) {
        const emojiUrl = `https://cdn.discordapp.com/emojis/${emoji.id}.${emoji.animated ? "gif" : "webp"}`;
        parseResult.content = parseResult.content.replace
            (`<${emoji.animated ? "a" : ""}:${emoji.originalName || emoji.name}:${emoji.id}>`,
             `[\n\\]](\n${emojiUrl + '?size=48'}\n) `);
    }

**Comment by DanzoGit** [comment]
@Thebomb32 Do you think this makes sense? Moderators can change the rule, or just ban you)

**Comment by Thebomb32** [comment]
> @Thebomb32 Do you think this makes sense? Moderators can change the rule, or just ban you)

The rule is in place to block malicious links. Given that this is just emojis, I hardly believe anyone in their right mind would care. For the rule thing yes, they can change the rule and more changes to the code are needed if it stops working in the future.
