### ISSUE TITLE
meta not found

### ISSUE THREAD

**Issue by Karma217** [EpicGazel/DiscordFreeEmojis#5]
**Describe the bug**
says meta not found and then doesn't appear in the list

**Screenshots**
![image](https://github.com/EpicGazel/DiscordFreeEmojis/assets/152862659/06d79b2b-660e-4049-a4cd-f3829b79ff9b)
**Client:**
 - Browser:  Brave / Desktop: win 10
 - Discord Build Channel : Release
 - BD Version 1.10.1

**Comment by DanzoGit** [comment]
You have incorrectly provided a link to the script. Correct link:
https://raw.githubusercontent.com/EpicGazel/DiscordFreeEmojis/master/DiscordFreeEmojis64px.plugin.js
or
https://raw.githubusercontent.com/EpicGazel/DiscordFreeEmojis/master/DiscordFreeEmojis.plugin.js

**Comment by EpicGazel** [comment]
@Karma217 Is this solved by redownloading the plugin?
