### ISSUE TITLE
Stickers?

### ISSUE THREAD

**Issue by Hackatoan** [EpicGazel/DiscordFreeEmojis#6]
get stickers working. 

also get rid of purple locked nitro section and favortes that are locked.

**Comment by DanzoGit** [comment]
> also get rid of purple locked nitro section and favortes that are locked.


To hide advertisement blocks, etc., I would recommend this - https://gist.github.com/TheSunCat/58fedaa19d6154ef3e4b2b676c286906.

**Comment by Hackatoan** [comment]
alright yeah that works for theming so leaves stickers?

**Comment by EpicGazel** [comment]
@Hackatoan See [SendStickersAsLinks](https://betterdiscord.app/plugin/SendStickersAsLinks) or [DiscordFreeStickers](https://github.com/riolubruh/DiscordFreeStickers). One should hopefully be fixed soon (as the latest Discord update broke a bunch).
