### ISSUE TITLE
favorites and most used. 

### ISSUE THREAD

**Issue by Hackatoan** [EpicGazel/DiscordFreeEmojis#7]
if you had nitro at one point animated emojis it shows grey scaled in that section. probably only affects small amount of people so if you dont want fix i might work on myself at one point. 

![image](https://github.com/EpicGazel/DiscordFreeEmojis/assets/62629253/4493ab53-19da-4d03-9e56-a295770b3372)

**Comment by DanzoGit** [comment]
@Hackatoan If you're using the CSS I provided earlier, just comment out the lines that contain "grayscale". This will make all emojis colorful.

**Comment by Hackatoan** [comment]
reference for everyone else, 

https://gist.github.com/TheSunCat/58fedaa19d6154ef3e4b2b676c286906
