### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by WalterDrake** [EpicGazel/DiscordFreeEmojis#8]
I have installed the plugin, but it doesn't work. When I choose an emoji that displays a text as ":disappear:" or ":thank_you:". I use BD version v1.10.2.

**Comment by EpicGazel** [comment]
@WalterDrake Try disabling other plugins and what version of DiscordFreeEmojis are you using?

**Comment by WalterDrake** [comment]
After disabling a plugin is called nitroperks, it has worked. Seemingly, nitroperks causes this. Thanks
